# Generated by Django 4.1 on 2023-10-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_alter_user_first_name_alter_user_last_name_and_more'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_document',
            name='select_BU',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
    ]
