# Generated by Django 4.1 on 2023-10-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_document_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_document',
            name='department',
        ),
    ]
