# Generated by Django 4.1 on 2023-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_company_company_name'),
        ('files', '0007_remove_file_document_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('department_name', 'company')},
        ),
    ]
