# Generated by Django 4.1 on 2023-10-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_document',
            name='agency',
            field=models.CharField(default='Default Agency Name', max_length=50),
        ),
    ]
