# Generated by Django 4.1 on 2023-10-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_alter_file_document_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_document',
            name='upload_file',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
